# Generated by Django 6.0.3 on 2026-03-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('company', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='medicines/')),
            ],
        ),
    ]
