# Generated by Django 6.0.3 on 2026-03-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bill_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
