# Generated by Django 6.0.3 on 2026-03-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_status_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='safety_warning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
