from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('login/', views.login_view),
    path('logout/', views.logout_view),
    path('signup/', views.signup_view),
    path('profile/', views.profile_view),
    path('add-to-cart/', views.add_to_cart),
    path('cart/', views.cart_view),
    path('remove-from-cart/', views.remove_from_cart),
    path('update-cart/', views.update_cart),
    path('checkout/', views.checkout),
    path('upload-prescriptions/', views.upload_prescriptions, name='upload_prescriptions'),
    path('orders/', views.orders_view, name='orders'),
    path('orders/<int:order_id>/', views.order_detail, name='order_detail'),
    path('dashboard/', views.dashboard),
    path('add-medicine/', views.add_medicine),
    path('upload-medicines-csv/', views.upload_medicines_csv),
    path('delete-medicine/', views.delete_medicine),
    path('edit-medicine/<int:id>/', views.edit_medicine),
    path('medicine/<int:id>/', views.medicine_detail),
    path('admin-orders/', views.admin_orders, name='admin_orders'),
    path('admin-orders/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('update-order-status/<int:order_id>/', views.update_order_status, name='update_order_status'),
    path('billing/', views.billing),
    path('add-to-bill/', views.add_to_bill),
    path('set-customer/', views.set_customer),
    path('generate-bill/', views.generate_bill),
    path('invoice/<int:id>/', views.invoice),
    path('remove-from-bill/', views.remove_from_bill),
    path('update-bill/', views.update_bill),
    path('download-invoice/<int:id>/', views.download_invoice, name='download_invoice'),
    path('form-demo/', views.add_form_demo),
    path('payment/<int:order_id>/', views.create_payment, name='create_payment'),
    path('verify-payment/', views.verify_payment),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('payment-failed/', views.payment_failed),
    path('checkout/', views.checkout, name='checkout'),
    path('payment/', views.create_payment, name='create_payment'),
    path('order-success/', views.order_success, name='order_success'),
]